### ISSUE TITLE
[ SECURITY ISSUE ] Why PyPI account password is stored in the repository?

### ISSUE THREAD

**Issue by artempronevskiy** [simple-salesforce/simple-salesforce#777]
https://github.com/simple-salesforce/simple-salesforce/blob/master/.travis.yml#L31

```yml
deploy:
  # Allow travis-ci to deploy new tags to PyPI
  provider: pypi
  edge:
    branch: v1.8.45
  username: simple-salesforce
  password:
    secure: "RdkngWbRCGN5qSOk4babeda3w0jhsxB+zbuPjnFIOCHYz3OOQkIccXsoFPJso/E4k35mRNTU1J6PEBeL9W3KEtSgsl6k3lX8jamgJzkZU/HPoV8OH5tvybd3uiSikKA6EoxS5yfGjgTuSdOo07AzS69X4+FxNkRnTnug37tLjds="
  distributions: "sdist bdist_wheel"
```

what's this? if pypi account password is shared for the entire world - everybody can use it to push modified package to pypi. or it's an old password used a long time ago to test the things out and it's not in use currently?
